In [3]:
pip install numpy

In [2]:
import numpy as np
print(np.__version__)

1.25.0


In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.full((3,3),True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1 ]

array([1, 3, 5, 7, 9])

In [8]:
arr[arr % 2 == 1 ] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [9]:
arr = np.arange(10)
out = np.where(arr % 2 == 1 ,-1,arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [10]:
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [12]:
c = np.concatenate((a,b),axis =0)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
d = np.vstack([a,b])
d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
a = np.array([1,2,3])

In [16]:
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [17]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [18]:
np.intersect1d(a,b)

array([2, 4])

In [19]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [20]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [21]:
np.setdiff1d(b,a)

array([6, 7, 8, 9])

In [22]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [23]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [24]:
# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]
#> (array([6, 9, 10]),)

# Method 3: (thanks loganzk!)
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [25]:
def maxx(x,y):
    if x>=y:
        return x
    else:
        return y
    
pair_max = np.vectorize(maxx,otypes=[float])

In [26]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [27]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
arr[:,[2,1,0]]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [29]:
arr[::-1,:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [30]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [31]:
rand_arr = np.random.uniform(5,10, size=(5,3))
rand_arr

array([[9.70580725, 6.50324935, 8.84080519],
       [7.12119272, 6.48576016, 5.2587215 ],
       [5.0085926 , 8.46066149, 5.15186662],
       [9.07862255, 7.20166164, 9.67179174],
       [8.55863461, 6.71157758, 6.64602283]])

In [32]:
rand_arr[:,:1]

array([[9.70580725],
       [7.12119272],
       [5.0085926 ],
       [9.07862255],
       [8.55863461]])

In [33]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)

(150,)


C:\Users\mukes\AppData\Local\Temp\ipykernel_3788\4287530268.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


In [34]:
species = np.array([row[4] for row in iris_1d])
species[:5]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S15')

In [35]:
h = iris_1d.reshape(-1,2)
h.shape

(75, 2)

In [36]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [37]:
iris_1d[0]

(5.1, 3.5, 1.4, 0.2, b'Iris-setosa')

In [38]:
np.mean([row[0] for row in iris_1d])

5.843333333333334

In [39]:
k = np.linalg.norm([row[0] for row in iris_1d])
print([row[0]/k for row in iris_1d])

[0.07056264100837592, 0.0677954786158906, 0.06502831622340527, 0.06364473502716259, 0.06917905981213325, 0.07471338459710393, 0.06364473502716259, 0.06917905981213325, 0.060877572634677274, 0.0677954786158906, 0.07471338459710393, 0.06641189741964793, 0.06641189741964793, 0.0594939914384346, 0.08024770938207458, 0.07886412818583191, 0.07471338459710393, 0.07056264100837592, 0.07886412818583191, 0.07056264100837592, 0.07471338459710393, 0.07056264100837592, 0.06364473502716259, 0.07056264100837592, 0.06641189741964793, 0.06917905981213325, 0.06917905981213325, 0.07194622220461859, 0.07194622220461859, 0.06502831622340527, 0.06641189741964793, 0.07471338459710393, 0.07194622220461859, 0.07609696579334659, 0.0677954786158906, 0.06917905981213325, 0.07609696579334659, 0.0677954786158906, 0.060877572634677274, 0.07056264100837592, 0.06917905981213325, 0.06226115383091993, 0.060877572634677274, 0.06917905981213325, 0.07056264100837592, 0.06641189741964793, 0.07056264100837592, 0.063644735027

In [40]:
np.percentile([row[0] for row in iris_1d],q=[5, 95])

array([4.6  , 7.255])

In [41]:
np.isnan(iris_2d[:, 0]).sum()

0

In [42]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Solution
print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))

Number of missing values: 
 4
Position of missing values: 
 (array([17, 25, 55, 75], dtype=int64),)


In [43]:
iris_2d[(iris_2d[:,2]>1.5 ) & (iris_2d[:,0] <5)]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [44]:
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Solution 1
np.corrcoef(iris[:, 0], iris[:, 2])[0, 1]

0.8717541573048712

In [45]:
np.isnan(iris_2d).any()

True

In [46]:
iris_2d[np.isnan(iris_2d)] = 0

In [47]:
np.unique([row[0] for row in iris_1d]).sum()

210.39999999999998

In [48]:
# Extract the species column as an array
species = np.array([row.tolist()[3] for row in iris])

# Get the unique values and the counts
np.unique(species, return_counts=True)

(array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6,
        1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5]),
 array([ 6, 28,  7,  7,  1,  1,  7,  3,  5, 13,  8, 12,  4,  2, 12,  5,  6,
         6,  3,  8,  3,  3], dtype=int64))

In [49]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica'], dtype='<U15')

In [52]:
print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5]


In [66]:
output = []
uniqs = np.unique(species_small)
print(uniqs)

for val in uniqs:  # uniq values in group
    for s in species_small[species_small==val]:  # each element in group
        groupid = np.argwhere(uniqs == s).tolist()[0][0]  # groupid
        output.append(groupid)
output

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]

In [68]:
a = np.random.randint(20, size=10)
print(a)
print(a.argsort().argsort())

[17 15  1 14  7 16  2  9 19  2]
[8 6 0 5 3 7 1 4 9 2]


In [73]:
a = np.random.randint(20, size=[2,5])
print(a)
print(a.ravel().argsort().argsort().reshape(2,5))
#first using ravel to make it one D then again reshape to 2,5

[[ 2 10 18 13 12]
 [ 1  6 10  0  2]]
[[2 5 9 8 7]
 [1 4 6 0 3]]


In [76]:
a = np.random.randint(1,10, [5,3])
print(a)
for row in a:
    print(max(row))

[[9 6 3]
 [8 6 1]
 [9 7 3]
 [1 6 4]
 [3 4 7]]
9
8
9
6
7


In [77]:
np.amax(a, axis=1)

array([9, 8, 9, 6, 7])

In [78]:
np.apply_along_axis(np.max, arr=a, axis=1)

array([9, 8, 9, 6, 7])

In [80]:
np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=a, axis=1)

array([0.33333333, 0.125     , 0.33333333, 0.16666667, 0.42857143])

In [4]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


# Solution
# No direct way to implement this. Just a version of a workaround.
numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4]  # species

# List comprehension version
[[group_val, numeric_column[grouping_column==group_val].mean()] for group_val in np.unique(grouping_column)]

[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.7700000000000005],
 [b'Iris-virginica', 2.974]]

In [11]:
pip install requests

                                              0.0/62.6 kB ? eta -:--:--
     ---------------------------------------  61.4/62.6 kB ? eta -:--:--
     ---------------------------------------- 62.6/62.6 kB 1.1 MB/s eta 0:00:00
                                              0.0/96.6 kB ? eta -:--:--
     --------------------------------------   92.2/96.6 kB 2.6 MB/s eta 0:00:01
     ---------------------------------------- 96.6/96.6 kB 1.1 MB/s eta 0:00:00
                                              0.0/61.5 kB ? eta -:--:--
     ---------------------------------------  61.4/61.5 kB ? eta -:--:--
     ---------------------------------------- 61.5/61.5 kB 1.1 MB/s eta 0:00:00
                                              0.0/123.6 kB ? eta -:--:--
     -------------------------------------  122.9/123.6 kB 7.5 MB/s eta 0:00:01
     -------------------------------------- 123.6/123.6 kB 2.4 MB/s eta 0:00:00
                                              0.0/157.0 kB ? eta -:--:--
     -------

In [13]:
from io import BytesIO
from PIL import Image
import PIL, requests

# Import image from URL
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)

# Read it as Image
I = Image.open(BytesIO(response.content))

# Optionally resize
I = I.resize([150,150])

# Convert to numpy array
arr = np.asarray(I)

# Optionaly Convert it back to an image and show
im = PIL.Image.fromarray(np.uint8(arr))
Image.Image.show(im)

In [14]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

In [15]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations

array([2, 5], dtype=int64)

In [16]:
# Input
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

# Solution
print(a_2d - b_1d[:,None])

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [18]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5
np.where(x == 1)[0][n-1]

8

In [19]:
# Input: a numpy datetime64 object
dt64 = np.datetime64('2018-02-25 22:10:10')

# Solution
from datetime import datetime
dt64.tolist()

# or

dt64.astype(datetime)
#> datetime.datetime(2018, 2, 25, 22, 10, 10)

datetime.datetime(2018, 2, 25, 22, 10, 10)

In [22]:
np.arange(5,5+10*3,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])