In [2]:
import pandas as pd

In [12]:
def subarraySum(arr,N,S):
    sum = 0
    for i in range(N):
        if sum < S:
            sum += arr[i]
        else:
            break
    return arr[0],arr[i-1]

In [13]:
arr = (1,2,3,4,5,6,7,8,9,10)
subarraySum(arr,10,15)

(1, 5)

In [14]:
arr = (1,2,3,7,5)
subarraySum(arr,5,12)

(1, 7)

In [18]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [30]:
ser = pd.Series(mydict)
type(ser)
df = ser.to_frame().reset_index()
df.head()

index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4

In [33]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

comb = pd.concat((ser1,ser2),axis=1)
comb

0  1
0  1  4
1  2  5
2  3  6
3  4  7
4  5  8

In [34]:
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

In [35]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

ser.value_counts()

d    8
h    5
c    4
g    4
f    3
a    3
b    2
e    1
Name: count, dtype: int64

In [36]:
ser = pd.Series(np.random.randint(1, 5, [12]))
ser

0     2
1     4
2     1
3     4
4     3
5     4
6     2
7     3
8     3
9     2
10    3
11    4
dtype: int32

In [37]:
np.argwhere(ser % 3==0)

array([[ 4],
       [ 7],
       [ 8],
       [10]], dtype=int64)

In [38]:
# Input
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

# Solution
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

In [40]:
# Input
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

# Output
# Vertical
df = pd.concat([ser1, ser2], axis=0)
print(df)

# Horizontal
df1 = pd.concat([ser1, ser2], axis=1)
print(df1)

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object
   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


In [42]:
# Input
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

# Solution 1
[np.where(i == ser1)[0].tolist()[0] for i in ser2]


[5, 4, 0, 8]

In [43]:

# Solution 2
[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

In [44]:
# Input
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

# Solution 1
ser.map(lambda x: x.title())

# Solution 2
ser.map(lambda x: x[0].upper() + x[1:])

# Solution 3
pd.Series([i.title() for i in ser])

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [55]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Solution 1
from dateutil.parser import parse
ser = ser.map(lambda x: parse(x))


In [59]:
print("Date: ", ser.dt.day.tolist())
print("Date: ", ser.dt.day_of_week.tolist())
print("Date: ", ser.dt.dayofyear.tolist())
print("Date: ", ser.dt.year.tolist())

Date:  [1, 2, 3, 4, 5, 6]
Date:  [4, 2, 5, 3, 0, 5]
Date:  [1, 33, 63, 94, 125, 157]
Date:  [2010, 2011, 2012, 2013, 2014, 2015]


In [64]:
ser.dt.year.astype(str)+'-'+ser.dt.month.astype(str)+'-'+'04'

0    2010-1-04
1    2011-2-04
2    2012-3-04
3    2013-4-04
4    2014-5-04
5    2015-6-04
dtype: object

In [65]:
# Input
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

# Solution
from collections import Counter
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
ser[mask]


0     Apple
1    Orange
4     Money
dtype: object

In [66]:
# Input
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])

# Solution 1 (as series of strings)
import re
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
mask = emails.map(lambda x: bool(re.match(pattern, x)))
emails[mask]

# Solution 2 (as series of list)
emails.str.findall(pattern, flags=re.IGNORECASE)

# Solution 3 (as list)
[x[0] for x in [re.findall(pattern, email) for email in emails] if len(x) > 0]

['rameses@egypt.com', 'matt@t.co', 'narendra@modi.com']

In [67]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Bin petallength 
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])

# Map it to respective category
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

# View
petal_length_cat[:4]


['small', 'small', 'small', 'small']

In [71]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution
# Compute volume
sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi*(petallength)*(sepallength**2))/3
volume = volume[:, np.newaxis]
out = np.hstack([iris_2d,volume])
out

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        33.238050274980004],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa',
        36.65191429188092],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa',
        51.911677007917746],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa',
        31.022180256648003],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa',
        39.269908169872416],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa',
        28.38324242763259],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa',
        37.714819806345474],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa',
        45.80442088933919],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa',
        38.603890527311

In [77]:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution
# Get the species column
species = iris[:, 4]

# Approach 1: Generate Probablistically
np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a, 150, p=[0.5, 0.25, 0.25])
print(np.unique(species_out, return_counts=True))

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='<U15'), array([77, 37, 36], dtype=int64))


In [78]:

# Approach 2: Probablistic Sampling (preferred)
np.random.seed(100)
probs = np.r_[np.linspace(0, 0.500, num=50), np.linspace(0.501, .750, num=50), np.linspace(.751, 1.0, num=50)]
index = np.searchsorted(probs, np.random.random(150))
species_out = species[index]
print(np.unique(species_out, return_counts=True))

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object), array([77, 37, 36], dtype=int64))


In [83]:
iris_p_len = iris[iris[:,4]==b'Iris-setosa',[2]].astype('float')
iris_p_len

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4])

In [84]:
print(iris[iris[:,0].argsort()][:20])

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.2' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.9' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.1' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.9' b'2.4' b'3.3' b'1.0' b'Iris-versicolor']
 [b'4.9' b'2.5' b'4.5' b'1.7' b'Iris-virginica']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [89]:
vals,counts = np.unique(iris[:,2],return_counts=True)
print(vals,counts)
print(vals[np.argmax(counts)])

[b'1.0' b'1.1' b'1.2' b'1.3' b'1.4' b'1.5' b'1.6' b'1.7' b'1.9' b'3.0'
 b'3.3' b'3.5' b'3.6' b'3.7' b'3.8' b'3.9' b'4.0' b'4.1' b'4.2' b'4.3'
 b'4.4' b'4.5' b'4.6' b'4.7' b'4.8' b'4.9' b'5.0' b'5.1' b'5.2' b'5.3'
 b'5.4' b'5.5' b'5.6' b'5.7' b'5.8' b'5.9' b'6.0' b'6.1' b'6.3' b'6.4'
 b'6.6' b'6.7' b'6.9'] [ 1  1  2  7 12 14  7  4  2  1  2  2  1  1  1  3  5  3  4  2  4  8  3  5
  4  5  4  8  2  2  2  3  6  3  3  2  2  3  1  1  1  2  1]
b'1.5'


In [92]:
np.argwhere(iris[:,3].astype('float')>1.0)[0]

array([50], dtype=int64)

In [98]:
a = np.random.uniform(1,50, 20)
print(a)
np.clip(a, a_min=10, a_max=30)

[30.65048974 28.40164688 43.15931535 46.0680126  42.63075896 13.46886024
 44.00022157 22.32137931 36.74522285 21.21939761 10.35096624 35.59495648
 12.79100823 42.71489691 41.38101217 26.73537754 19.93069892 29.95315875
  7.73865713 40.60524999]


array([30.        , 28.40164688, 30.        , 30.        , 30.        ,
       13.46886024, 30.        , 22.32137931, 30.        , 21.21939761,
       10.35096624, 30.        , 12.79100823, 30.        , 30.        ,
       26.73537754, 19.93069892, 29.95315875, 10.        , 30.        ])

In [103]:
a[a.argsort()][-5:]

array([42.63075896, 42.71489691, 43.15931535, 44.00022157, 46.0680126 ])

In [108]:
print(a.argsort())

[18 10 12  5 16  9  7 15  1 17  0 11  8 19 14  4 13  2  6  3]


In [113]:
arr = np.random.randint(1,11,size=(6, 10))
def counts_of_all_values_rowwise(arr2d):
    # Unique values and its counts row wise
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]

    # Counts of all values row wise
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])

# Print
print(np.arange(1,11))
counts_of_all_values_rowwise(arr)

[ 1  2  3  4  5  6  7  8  9 10]


C:\Users\mukes\AppData\Local\Temp\ipykernel_8804\2547585372.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])


[[0, 0, 2, 1, 1, 0, 2, 2, 0, 2],
 [2, 1, 1, 2, 2, 1, 0, 0, 1, 0],
 [0, 1, 2, 2, 1, 0, 2, 1, 1, 0],
 [1, 0, 1, 2, 1, 0, 2, 2, 0, 1],
 [2, 2, 0, 2, 1, 1, 1, 0, 1, 0],
 [3, 0, 1, 0, 0, 0, 2, 1, 2, 1]]

In [114]:
arr = np.array([np.array(list('bill clinton')), np.array(list('narendramodi')), np.array(list('jjayalalitha'))])
print(np.unique(arr))
counts_of_all_values_rowwise(arr)

[' ' 'a' 'b' 'c' 'd' 'e' 'h' 'i' 'j' 'l' 'm' 'n' 'o' 'r' 't' 'y']


C:\Users\mukes\AppData\Local\Temp\ipykernel_8804\2547585372.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])


[[1, 0, 1, 1, 0, 0, 0, 2, 0, 3, 0, 2, 1, 0, 1, 0],
 [0, 2, 0, 0, 2, 1, 0, 1, 0, 0, 1, 2, 1, 2, 0, 0],
 [0, 4, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 1, 1]]

In [115]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
species_small

output = []
uniqs = np.unique(species_small)

for val in uniqs:  # uniq values in group
    for s in species_small[species_small==val]:  # each element in group
        groupid = np.argwhere(uniqs == s).tolist()[0][0]  # groupid
        output.append(groupid)

print(output)

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]


In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [4]:
df.isna().sum()

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags               38
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

In [8]:
d = {'Min.Price': np.nanmean, 'Max.Price': np.nanmedian}
df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d, ))

In [9]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

# Solution
type(df[['a']])
type(df.loc[:, ['a']])
type(df.iloc[:, [0]])

pandas.core.frame.DataFrame

In [10]:
# Input
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])

# Solution 1: Rounding
df.round(4)

# Solution 2: Use apply to change format
df.apply(lambda x: '%.4f' % x, axis=1)
# or
df.applymap(lambda x: '%.4f' % x)

# Solution 3: Use set_option
pd.set_option('display.float_format', lambda x: '%.4f' % x)

# Solution 4: Assign display.float_format
pd.options.display.float_format = '{:.4f}'.format
print(df)

# Reset/undo float formatting
pd.options.display.float_format = None

   random
0  0.0001
1  0.9469
2  0.1485
3  0.0000


C:\Users\mukes\AppData\Local\Temp\ipykernel_12016\2662863825.py:8: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.apply(lambda x: '%.4f' % x, axis=1)


In [13]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
print(df.iloc[::20, :][['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [14]:
df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
print(df.index.is_unique)

True


In [15]:
df

Manufacturer    Model     Type  Min.Price  Price  \
Acura_Integra_Small              Acura  Integra    Small       12.9   15.9   
missing_Legend_Midsize         missing   Legend  Midsize       29.2   33.9   
Audi_90_Compact                   Audi       90  Compact       25.9   29.1   
Audi_100_Midsize                  Audi      100  Midsize        NaN   37.7   
BMW_535i_Midsize                   BMW     535i  Midsize        NaN   30.0   
...                                ...      ...      ...        ...    ...   
Volkswagen_Eurovan_Van      Volkswagen  Eurovan      Van       16.6   19.7   
Volkswagen_Passat_Compact   Volkswagen   Passat  Compact       17.6   20.0   
Volkswagen_Corrado_Sporty   Volkswagen  Corrado   Sporty       22.9   23.3   
Volvo_240_Compact                Volvo      240  Compact       21.8   22.7   
missing_850_Midsize            missing      850  Midsize       24.8   26.7   

                           Max.Price  MPG.city  MPG.highway  \
Acura_Integra_Small             18.8      25.0         31.0   
missing_Legend_Midsize          38.7      18.0         25.0   
Audi_90_Compact                 32.3      20.0         26.0   
Audi_100_Midsize                44.6      19.0         26.0   
BMW_535i_Midsize                 NaN      22.0         30.0   
...                              ...       ...          ...   
Volkswagen_Eurovan_Van          22.7      17.0         21.0   
Volkswagen_Passat_Compact       22.4      21.0         30.0   
Volkswagen_Corrado_Sporty       23.7      18.0         25.0   
Volvo_240_Compact               23.5      21.0         28.0   
missing_850_Midsize             28.5      20.0         28.0   

                                      AirBags DriveTrain  ... Passengers  \
Acura_Integra_Small                       NaN      Front  ...        5.0   
missing_Legend_Midsize     Driver & Passenger      Front  ...        5.0   
Audi_90_Compact                   Driver only      Front  ...        5.0   
Audi_100_Midsize           Driver & Passenger        NaN  ...        6.0   
BMW_535i_Midsize                          NaN       Rear  ...        4.0   
...                                       ...        ...  ...        ...   
Volkswagen_Eurovan_Van                    NaN      Front  ...        7.0   
Volkswagen_Passat_Compact                 NaN      Front  ...        5.0   
Volkswagen_Corrado_Sporty                 NaN      Front  ...        4.0   
Volvo_240_Compact                 Driver only       Rear  ...        5.0   
missing_850_Midsize        Driver & Passenger      Front  ...        5.0   

                           Length  Wheelbase  Width  Turn.circle  \
Acura_Integra_Small         177.0      102.0   68.0         37.0   
missing_Legend_Midsize      195.0      115.0   71.0         38.0   
Audi_90_Compact             180.0      102.0   67.0         37.0   
Audi_100_Midsize            193.0      106.0    NaN         37.0   
BMW_535i_Midsize            186.0      109.0   69.0         39.0   
...                           ...        ...    ...          ...   
Volkswagen_Eurovan_Van      187.0      115.0   72.0         38.0   
Volkswagen_Passat_Compact   180.0      103.0   67.0         35.0   
Volkswagen_Corrado_Sporty   159.0       97.0   66.0         36.0   
Volvo_240_Compact           190.0      104.0   67.0         37.0   
missing_850_Midsize         184.0      105.0   69.0         38.0   

                          Rear.seat.room  Luggage.room  Weight   Origin  \
Acura_Integra_Small                 26.5           NaN  2705.0  non-USA   
missing_Legend_Midsize              30.0          15.0  3560.0  non-USA   
Audi_90_Compact                     28.0          14.0  3375.0  non-USA   
Audi_100_Midsize                    31.0          17.0  3405.0  non-USA   
BMW_535i_Midsize                    27.0          13.0  3640.0  non-USA   
...                                  ...           ...     ...      ...   
Volkswagen_Eurovan_Van              34.0           NaN  3960.0      NaN   
Vo

In [17]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))

# Solution
n = 5
df['a'].argsort()[::-1][n]

9

In [18]:
df.iloc[::-1, :]

a   b   c
9  23  29  15
8  26  24  25
7  23  19  15
6   1   8   7
5  24  19  20
4   5  21  21
3  27  29  20
2  26   9  19
1   9  27  22
0  18  26  29

In [23]:
print(df)
df.apply(np.argmax, axis=1).value_counts()

    a   b   c
0  18  26  29
1   9  27  22
2  26   9  19
3  27  29  20
4   5  21  21
5  24  19  20
6   1   8   7
7  23  19  15
8  26  24  25
9  23  29  15


1    5
0    4
2    1
Name: count, dtype: int64

In [8]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))
print(df)

# Solution
abs_corrmat = np.abs(df.corr())
print(abs_corrmat)
max_corr = abs_corrmat.apply(lambda x: sorted(x)[-2])
print(max_corr)
print('Maximum Correlation possible for each column: ', np.round(max_corr.tolist(), 2))

    p   q   r   s   t   u   v   w   x   y
a  26  69  38  97  44  50  15  95  15  89
b  61  23  14   8  85  46  93  17   8  50
c  28  52  77  18  35  70  70  51  30  50
d  17  23   5  98  99  89  26  36  85  65
e  26  72  37  80  14  49   6  11  31  46
f  84  13  43  50  88  21  55  29  38  26
g  29  68  94  81  95  27  36  62  23  62
h  31  16  20  25  59  30  62  50  47  20
          p         q         r         s         t         u         v  \
p  1.000000  0.539748  0.077715  0.458840  0.347320  0.575046  0.530565   
q  0.539748  1.000000  0.581979  0.483458  0.554653  0.064939  0.606103   
r  0.077715  0.581979  1.000000  0.020461  0.120224  0.290453  0.043843   
s  0.458840  0.483458  0.020461  1.000000  0.039857  0.219119  0.923745   
t  0.347320  0.554653  0.120224  0.039857  1.000000  0.107305  0.311199   
u  0.575046  0.064939  0.290453  0.219119  0.107305  1.000000  0.170194   
v  0.530565  0.606103  0.043843  0.923745  0.311199  0.170194  1.000000   
w  0.380354  0.383408 

In [11]:
min_max = df.apply(lambda x: np.min(x)/np.max(x), axis= 1)
min_max

a    0.154639
b    0.086022
c    0.233766
d    0.050505
e    0.075000
f    0.147727
g    0.242105
h    0.258065
dtype: float64

In [26]:
out = df.apply(lambda x: x.sort_values().unique()[-1], axis =1)
print(df)
print(out)

    p   q   r   s   t   u   v   w   x   y
a  26  69  38  97  44  50  15  95  15  89
b  61  23  14   8  85  46  93  17   8  50
c  28  52  77  18  35  70  70  51  30  50
d  17  23   5  98  99  89  26  36  85  65
e  26  72  37  80  14  49   6  11  31  46
f  84  13  43  50  88  21  55  29  38  26
g  29  68  94  81  95  27  36  62  23  62
h  31  16  20  25  59  30  62  50  47  20
a    97
b    93
c    77
d    99
e    80
f    88
g    95
h    62
dtype: int32


In [27]:
# Solution Q1
out1 = df.apply(lambda x: ((x - x.mean())/x.std()).round(2))
print('Solution Q1\n',out1)

# Solution Q2
out2 = df.apply(lambda x: ((x.max() - x)/(x.max() - x.min())).round(2))
print('Solution Q2\n', out2)  

Solution Q1
       p     q     r     s     t     u     v     w     x     y
a -0.52  1.05 -0.10  1.09 -0.66  0.10 -1.02  1.89 -0.82  1.73
b  1.02 -0.74 -0.88 -1.34  0.64 -0.08  1.60 -0.99 -1.12 -0.05
c -0.43  0.39  1.17 -1.07 -0.95  0.97  0.83  0.26 -0.19 -0.05
d -0.91 -0.74 -1.17  1.12  1.08  1.80 -0.65 -0.29  2.12  0.64
e -0.52  1.16 -0.13  0.62 -1.61  0.05 -1.33 -1.22 -0.15 -0.23
f  2.04 -1.13  0.07 -0.19  0.73 -1.17  0.32 -0.55  0.14 -1.14
g -0.39  1.01  1.73  0.65  0.96 -0.91 -0.32  0.67 -0.49  0.50
h -0.30 -1.01 -0.68 -0.88 -0.19 -0.78  0.56  0.23  0.52 -1.41
Solution Q2
       p     q     r     s     t     u     v     w     x     y
a  0.87  0.05  0.63  0.01  0.65  0.57  0.90  0.00  0.91  0.00
b  0.34  0.83  0.90  1.00  0.16  0.63  0.00  0.93  1.00  0.57
c  0.84  0.34  0.19  0.89  0.75  0.28  0.26  0.52  0.71  0.57
d  1.00  0.83  1.00  0.00  0.00  0.00  0.77  0.70  0.00  0.35
e  0.87  0.00  0.64  0.20  1.00  0.59  1.00  1.00  0.70  0.62
f  0.00  1.00  0.57  0.53  0.13  1.00  0.44 

In [29]:
for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0
df

p   q   r   s   t   u   v   w   x   y
a   0  69  38  97  44  50  15   0  15  89
b  61   0  14   8  85  46   0  17   8  50
c  28  52   0  18  35   0  70  51  30  50
d  17  23   5   0   0  89  26  36  85  65
e  26  72  37   0   0  49   6  11  31  46
f  84  13   0  50  88   0  55  29  38  26
g  29   0  94  81  95  27   0  62  23  62
h   0  16  20  25  59  30  62   0  47  20

In [31]:
# Input
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

print(df)

# Solution
df_grpd = df['taste'].groupby(df.fruit)
df_grpd.get_group('banana').sort_values().iloc[-3]

    fruit     taste  price
0   apple  0.986164     10
1  banana  0.477163      1
2  orange  0.696771     11
3   apple  0.290113      8
4  banana  0.381137     12
5  orange  0.159026     10
6   apple  0.023130      5
7  banana  0.968245      7
8  orange  0.474017      0


0.38113748883082865